# Generated by Django 5.2.1 on 2025-05-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfidf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='wordanalysis',
            name='text_file',
        ),
        migrations.DeleteModel(
            name='TextFile',
        ),
        migrations.DeleteModel(
            name='WordAnalysis',
        ),
    ]
