# Generated by Django 5.2.1 on 2025-05-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfidf', '0002_uploadedtext_remove_wordanalysis_text_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedtext',
            name='text_hash',
            field=models.CharField(db_index=True, default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedtext',
            name='text',
            field=models.TextField(),
        ),
    ]
