# Generated by Django 5.2.1 on 2025-05-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfidf', '0004_fileupload_tfidfmetric_delete_uploadedtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
