# Generated by Django 5.2.1 on 2025-05-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfidf', '0005_fileupload_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfidfmetric',
            name='score',
        ),
    ]
