version: '3.9'

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/static
      - media_data:/app/media
      - vue_dist:/usr/share/nginx/html
    depends_on:
      - web
    networks:
      - backend

  web:
    build: .
    container_name: django_web
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - postgres
      - redis
      - mongo
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
    container_name: vue_builder
    volumes:
      - vue_dist:/usr/share/nginx/html
    networks:
      - backend
    command: echo "Build-only container"

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - backend

  mongo:
    image: mongo:6-jammy
    container_name: mongo_db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  celery:
    container_name: celery_worker
    image: django_web
    build: .
    command: celery -A config worker --loglevel=info --concurrency=4
    depends_on:
      - redis
      - postgres
      - mongo
    env_file:
      - .env
    networks:
      - backend


volumes:
  postgres_data:
  mongo_data:
  static_data:
  media_data:
  vue_dist:

networks:
  backend:
    driver: bridge
