services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tfidf_web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - mongo
    restart: always
    env_file:
      - .env

  mongo:
    image: mongo:7-jammy
    container_name: tfidf_mongo
    volumes:
      - mongo_data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: ["mongod", "--auth", "--bind_ip", "127.0.0.1", "--quiet"]


  nginx:
    image: nginx:stable-alpine
    container_name: tfidf_nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    restart: always

volumes:
  mongo_data:
